sudo: false

language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - cmake
      - python-numpy
      - python-pandas
      - python-virtualenv

before_install:
  - pip install pep8

install:
  - ./codestyle_checks.sh
  - mkdir build
  - pushd build && cmake .. && make -j && popd
  - cp build/3rdparty/protobuf-cmake/protoc/protoc 3rdparty/protobuf/src/
  - pushd 3rdparty/protobuf/python && python setup.py build && python setup.py install && popd

before_script:
  - pushd python/examples && ./download_datasets.sh && popd

script:
  - export PYTHONPATH=`pwd`/python:$PYTHONPATH
  - export ARTM_SHARED_LIBRARY=`pwd`/build/src/artm/libartm.so
  - pushd build/src/artm_tests && ./artm_tests && popd
  - pushd python/tests && python tests.py && popd
  - pushd python/examples && for f in *.py ; do echo "==== $f ====" && python "$f" ; done && popd
