# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

configuration:
  - Release

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories
shallow_clone: true

# clone directory
clone_folder: C:\projects\bigartm

# scripts to run before build
before_build:
  - cmd: cd C:\projects\bigartm
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

build:
  project: C:\projects\bigartm\build\bigartm.sln    # path to Visual Studio solution or project
  parallel: true                                    # enable MSBuild parallel builds
  verbosity: normal                                 # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off

# Enable RDP connection to test server as described here: http://www.appveyor.com/docs/how-to/rdp-to-build-worker
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
