version: 1.0.{build}
os: Windows Server 2012 R2
configuration:
- Release
platform: x64
shallow_clone: true
clone_folder: C:\bigartm
# need to install nuget packages before Visual Studio starts to make ANTLR targets available.
build_script:
- cd c:\bigartm
- utils\.nuget\nuget install -o utils utils\packages.config
- mkdir build
- cd build
- cmake .. -G"Visual Studio 14 Win64"
- cd ..
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
